package:
  name: scippneutron
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - gxx_linux-64 11.1.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - scipp {{ scipp }}
    - tbb-devel
  run:
    - pooch
    - python {{ python }}
    - scipp {{ scipp }}
    - h5py
    - scipy

test:
  imports:
    - scippneutron
    - neutron
  requires:
    - h5py
    - ipykernel = 6.3.1  # see https://github.com/ipython/ipykernel/issues/771
    - ipywidgets
    - matplotlib-base
    - psutil
    - pytest
    - pytest-asyncio
    - pythreejs
    - mantid-framework [not win]
    - python-confluent-kafka [linux64]
    - ess-streaming-data-types [linux64]
  source_files:
    - python/tests/
    - neutron/
  commands:
    - python -m pytest -v python

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - SCIPP_INSTALL_PREFIX
  script:
    - python tools/build_conda.py

about:
  home: https://github.com/scipp/scippneutron
  license: BSD-3-Clause
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction
  dev_url: https://github.com/scipp/scippneutron
  doc_url: https://scipp.github.io/scippneutron
