parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false
- name: scipp_channel
  type: string
  default: scipp

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main
  pipelines:
  - pipeline: upstream_scipp_main
    project: scipp
    source: Main
    trigger: none # TODO need to disable publishing and change back to `true`, once CI setup has been updated
    #parameters: # TODO does setting the parameter within the same file work?
    #  scipp_channel: scipp/label/dev

trigger:
  - main

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp --channel ess-dmsc'
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-no-mantid.yml'
      windows:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-no-mantid.yml'
    deploy: true
    conda_label: 'dev'
