parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false
- name: scipp_channel
  type: string
  default: scipp/label/dev

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

# New releases of scipp will automatically cause this pipeline to run
resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main
  pipelines:
  - pipeline: upstream_scipp_release
    project: scipp
    source: Main
    trigger: true 

trigger:
  - next

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp/label/dev --channel ess-dmsc'
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-next.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-next.yml'
      windows:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-no-mantid-next.yml'
    deploy: true
    conda_label: 'next'
    publish_docs: false
