parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main  # TODO: change to tag once new tag is created in pipelines repo

trigger:
  tags:
    include:
      - '*.*.*'

schedules:
  - cron: "0 0 * * *"
    displayName: 'Nightly dev build'
    branches:
      include:
        - 'main'
    always: false


pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp --channel ess-dmsc'
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7', '3.8']
        conda_env: 'scippneutron-developer.yml'
      osx:
        py_versions: ['3.7', '3.8']
        conda_env: 'scippneutron-developer-osx.yml'
      windows:
        py_versions: ['3.7', '3.8']
        conda_env: 'scippneutron-developer-no-mantid.yml'
    package: true
    deploy: true
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  # nightly
      conda_label: 'dev'
    ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  # tagged release
      conda_label: 'main'
      release: true
