parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false
- name: conda_channels
  type: object
  default:
    main: '--channel scipp/label/main --channel ess-dmsc'
    next: '--channel scipp/label/dev --channel ess-dmsc'

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: ${{ parameters.conda_channels['Build.SourceBranchName'] }}
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer.yml'
      # windows:
      #   py_versions: ['3.7']
      #   conda_env: 'scippneutron-developer-no-mantid.yml'
