parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: refs/tags/1.0.0

trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp --channel ess-dmsc'
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7', '3.8']
        conda_env: 'scippneutron-developer.yml'
      osx:
        py_versions: ['3.7', '3.8']
        conda_env: 'scippneutron-developer-osx.yml'
      windows:
        py_versions: ['3.7', '3.8']
        conda_env: 'scippneutron-developer-no-mantid.yml'
    deploy: true
    conda_label: 'main'
    release: true
