name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true  # cancel jobs from previous push

jobs:
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/static.txt
      - run: tox -e static
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic formatting

  build_and_test:
    needs: formatting
    name: build and test ${{ matrix.variant.os }}, py${{ matrix.python-version }}
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    env:
      PYTHONPATH: ${{ github.workspace }}/install
    strategy:
      fail-fast: false
      matrix:
        variant:
        - {os: ubuntu-20.04, cmake-preset: ci-linux}
        - {os: macos-11, cmake-preset: ci-macos}
        - {os: windows-2019, cmake-preset: ci-windows}
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - uses: ilammy/msvc-dev-cmd@v1  # Required to set up MSVC dev environment for Ninja builds.

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ci
          environment-file: .buildconfig/${{ matrix.variant.cmake-preset }}.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.2
        with:
          key: ${{ matrix.variant.os }}

      - name: Cache conan setup
        id: conan-cache-key
        run: |
          echo "::set-output name=key::$(/bin/date -u "+%Y%m%d")"
          echo "::set-output name=path::$(conan config home)"
      - name: Cache conan
        uses: actions/cache@v1
        with:
          path: ${{ steps.conan-cache-key.outputs.path }}
          key: conan-${{ matrix.variant.os }}-${{ steps.conan-cache-key.outputs.key }}

      - run: cmake --preset ${{ matrix.variant.cmake-preset }}
      - run: cmake --build --preset build
      - run: ctest --preset test

      - run: python -m pytest -v tests

      - run: |
          python -m sphinx -j2 -v -b html -d doctrees docs html
          python -m sphinx -j2 -v -b doctest -d doctrees docs html
          find html -type f -name "*.ipynb" -not -path "html/_sources/*" -delete
        if: ${{ contains(matrix.variant.os, 'ubuntu') }}

      - run: python -m sphinx -j4 -v -b linkcheck -d doctrees docs html
        # Linkcheck can be flaky. Avoid randomly breaking PR builds by running only on `main`
        if: ${{ contains(matrix.os, 'ubuntu') && github.ref == 'refs/heads/main' }}

      - uses: actions/upload-artifact@v2
        if: ${{ contains(matrix.os, 'ubuntu') }}
        with:
          name: DocumentationHTML
          path: html/
